name: loren
favicon: null
layout_spectrum: 0.24924
typography_spectrum: 0.19282
title: 'life by the sea in #encinitas #california'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e1ed'
    - '#000000'
    - '#0144ed'
    - '#05c7f8'
    - '#0183f2'
  brandStrength: 0.8915763488039374
  lightness: 0.08214626461267471
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
